using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Reflection;
using runnerDotNet;
namespace runnerDotNet
{
	public static partial class RunnerSettings
	{
		public static void Defaults()
		{
			GlobalVars.runnerProjectDefaults = new XVar(new XVar( "detailedError", true,
"createRestAPI", false,
"restAPIReturnEncodedBinary", false,
"restAPIAcceptEncodedBinary", false,
"restAPIAuthType", "none",
"restAPIKey", "",
"restAPIKeyField", "",
"enableWebreports", false,
"cookieBanner", false,
"emailTemplates", new XVar(  ),
"landingSettings", new XVar( "type", 1,
"table", "<global>",
"pageId", "menu",
"page", "menu",
"url", "" ),
"rteType", "BASIC",
"richTextEnabled", false,
"section508Compat", false,
"menuIds", XVar.Array(),
"tablesAdvSecurity", new XVar( "__meta__", 1,
"__object__", new XVar( "advSecurity", 0,
"usersOwnerIdField", "" ) ),
"customTemplates", XVar.Array(),
"mysqlCharsetName", "utf8",
"styleOverrides", new XVar(  ),
"hasCustomCss", false,
"hasCustomFunctionsJs", false,
"connEncryptInfo", new XVar(  ),
"userTableKeys", XVar.Array(),
"phpSpreadsheet", true,
"security", new XVar( "__meta__", 0,
"__object__", new XVar( "projectName", "",
"loginDataSource", "",
"loginForm", 3,
"dynamicPermissions", false,
"dpTablePrefix", "",
"dpTableConnId", "",
"providers", new XVar( "__meta__", 2,
"__object__", new XVar(  ) ),
"enabled", false,
"advancedSecurityAvailable", false,
"userGroupsAvailable", false,
"hardcodedLogin", false,
"defaultProviderCode", "",
"adOnlyLogin", false,
"sessionControl", new XVar( "__meta__", 0,
"__object__", new XVar( "lifeTime", 15,
"sessionName", "OEuiW2oLN90bTs4wuahB",
"JWTSecret", "zGy5waHoROAHkYEmqbDm" ) ),
"registration", new XVar( "__meta__", 0,
"__object__", new XVar( "remindMethod", 0,
"hashAlgorithm", 0,
"passwordValidation", new XVar( "__meta__", 0,
"__object__", new XVar( "strong", false,
"minimumLength", 8,
"uniqueCharacters", 4,
"digitsAndSymbols", 2,
"upperAndLowerCase", false ) ) ) ),
"captchaSettings", new XVar( "__meta__", 0,
"__object__", new XVar( "captchaType", 0,
"siteKey", "",
"secretKey", "",
"passesCount", 5 ) ),
"emailSettings", new XVar( "__meta__", 0,
"__object__", new XVar( "fromEmail", "",
"usePHPDefinedSMTP", false,
"useBuiltInMailer", false,
"SMTPServer", "localhost",
"SMTPPort", 25,
"SMTPUser", "",
"SMTPPassword", "",
"securityProtocol", 0 ) ),
"advancedSecurity", new XVar( "__meta__", 0,
"__object__", new XVar( "allowGuestLogin", false ) ),
"auditAndLocking", new XVar( "__meta__", 0,
"__object__", new XVar( "loggingMode", 0,
"loggingTable", new XVar( "__meta__", 0,
"__object__", new XVar( "connId", "",
"table", "" ) ),
"loggingFile", "audit.log",
"logSecurityActions", false,
"lockAfterUnsuccessfulLogin", false,
"enableLocking", false,
"lockingTable", new XVar( "__meta__", 0,
"__object__", new XVar( "connId", "",
"table", "" ) ),
"tables", new XVar( "__meta__", 1,
"__object__", new XVar(  ) ) ) ),
"twoFactorSettings", new XVar( "__meta__", 0,
"__object__", new XVar( "available", false,
"required", false,
"enable", true,
"remember", true,
"types", new XVar(  ),
"twoFactorField", "",
"emailField", "",
"phoneField", "",
"codeField", "",
"projectName", "" ) ),
"staticPermissions", new XVar( "__meta__", 0,
"__object__", new XVar( "groups", new XVar( "__meta__", 1,
"__object__", new XVar( "permissions", new XVar( "__meta__", 1,
"__object__", new XVar( "mask", "",
"table", "",
"restrictedPages", new XVar(  ) ) ) ) ) ) ),
"dbProvider", new XVar( "__meta__", 0,
"__object__", new XVar( "type", "%db" ) ) ) ),
"cloudSettings", new XVar( "__meta__", 0,
"__object__", new XVar( "cloudAmazonRegion", "",
"cloudAmazonBucket", "",
"cloudAmazonAccessKey", "",
"cloudAmazonSecretKey", "",
"cloudWasabiRegion", "",
"cloudWasabiBucket", "",
"cloudWasabiAccessKey", "",
"cloudWasabiSecretKey", "",
"cloudGDriveClientId", "",
"cloudGDriveClientSecret", "",
"cloudOneDriveClientId", "",
"cloudOneDriveClientSecret", "",
"cloudOneDriveDrive", "",
"cloudOneDriveAccountType", 0,
"cloudOneDriveDirectoryId", "",
"cloudDropboxClientId", "",
"cloudDropboxClientSecret", "" ) ),
"mapSettings", new XVar( "__meta__", 0,
"__object__", new XVar( "embed", true,
"provider", 0,
"apikey", "" ) ),
"smsSettings", new XVar( "__meta__", 0,
"__object__", new XVar( "smsProvider", 4,
"iBusername", "",
"iBpassword", "",
"iBsender", "",
"essUsername", "",
"essPassword", "",
"essSender", "",
"gwApiToken", "",
"gwSender", "",
"mbAuth", "",
"mbSender", "",
"twilioSID", "",
"twilioAuth", "",
"twilioNumber", "",
"phoneField", "",
"counryCode", "+1",
"wauUsername", "",
"wauPassword", "",
"wauSender", "" ) ) ));
			GlobalVars.runnerTableDefaults = new XVar(new XVar( "name", "",
"type", 0,
"shortName", "",
"advancedSecurityType", 0,
"pagesByType", new XVar(  ),
"pageTypes", new XVar(  ),
"defaultPages", new XVar(  ),
"tableOwnerIdField", "",
"usersOwnerIdField", "",
"scrollGridBody", false,
"hasEncryptedFields", false,
"listAjax", false,
"audit", false,
"locking", false,
"afterEditAction", 1,
"afterEditDetails", "",
"closePopupAfterEdit", true,
"afterAddAction", 1,
"afterAddDetail", "",
"closePopupAfterAdd", true,
"hasFieldMaps", false,
"detailsBadgeColor", "",
"pageOrientation", 0,
"printFitToPage", true,
"printScale", 100,
"pageSizeRecords", 20,
"pageSizeGroups", 5,
"pageSizePrintRecords", 40,
"pageSizePrintGroups", 3,
"pageSizeSelectorRecords", XVar.Array(),
"pageSizeSelectorGroups", XVar.Array(),
"displayLoading", false,
"resizeColumns", false,
"warnLeavingEdit", false,
"hideEmptyFieldsOnView", false,
"strOrderBy", "",
"orderInfo", XVar.Array(),
"sql", "",
"limitRecords", 0,
"keyFields", XVar.Array(),
"deviceHideFields", new XVar(  ),
"fields", new XVar( "__meta__", 1,
"__object__", new XVar( "name", "",
"goodName", "",
"strField", "",
"sourceSingle", "",
"index", 0,
"type", 200,
"autoinc", false,
"encrypted", false,
"restDateFormat", "",
"sqlExpression", "",
"deleteFile", false,
"basicUpload", false,
"absolutePath", false,
"uploadFolder", "files",
"codeUploadFolder", "",
"codeUploadFolderLang", "cs",
"viewFormats", new XVar( "__meta__", 1,
"__object__", new XVar( "format", "",
"pageType", "view",
"imageWidth", 600,
"imageHeight", 400,
"imageThumbWidth", 200,
"imageThumbHeight", 150,
"imageUrl", false,
"imageMultipleMode", 1,
"imageMaxCount", 0,
"imageGallery", true,
"imageCaptions", 2,
"imageCaptionField", "",
"imageBorder", true,
"imageMobileFullWidth", true,
"imageShowThumbnail", false,
"linkNewWindow", false,
"linkDisplay", 0,
"linkDisplayField", "",
"linkDisplayText", new XVar( "text", "Link",
"type", 0 ),
"linkPrefix", "",
"customExpressionLang", "cs",
"customExpression", "",
"fileCustomExpression", "",
"fileCustomExpressionLang", "cs",
"fileShowCustom", false,
"fileShowSize", false,
"fileShowIcon", true,
"fileShowPdf", false,
"fileFilenameField", "",
"mapWidth", 300,
"mapHeight", 225,
"mapZoom", 15,
"mapAddressField", "",
"mapLatField", "",
"mapLonField", "",
"mapDescriptionField", "",
"mapMarkerIcon", "",
"mapMarkerCodeExpression", false,
"mapMarkerLang", "cs",
"videoTitleField", "",
"videoWidth", 300,
"videoHeight", 200,
"videoFieldContainsFileURL", false,
"videoRewindEnabled", true,
"videoPluginInitString", "",
"numberFractionalDigits", 2,
"fieldEvents", new XVar( "__meta__", 2,
"__object__", new XVar( "event", "",
"handlerId", 0 ) ),
"textShowFirst", true,
"textShowFirstN", 80,
"timeFormat", 0,
"timeShowSeconds", true,
"timeShowDays", true,
"pluginInitString", "" ) ),
"editFormats", new XVar( "__meta__", 1,
"__object__", new XVar( "format", "Text field",
"pageType", "edit",
"required", false,
"defaultValue", "",
"defaultValueLang", "cs",
"autoUpdateValue", "",
"autoUpdateLang", "cs",
"validateAs", "",
"validateRegex", "",
"validateRegexMessage", new XVar( "text", "The value is invalid",
"type", 0 ),
"denyDuplicate", false,
"denyDuplicateMessage", new XVar( "text", "Value %value% already exists",
"type", 0 ),
"textboxSize", 200,
"textboxMaxLenth", 0,
"textboxMask", "",
"textInsertNull", false,
"textHTML5Input", "text",
"textareaHeight", 100,
"textareaRTE", false,
"lookupSize", 1,
"lookupMultiselect", false,
"lookupType", 1,
"lookupValues", XVar.Array(),
"lookupTable", "",
"lookupTableConnection", "",
"lookupLinkField", "",
"lookupDisplayField", "",
"lookupCustomDisplay", false,
"lookupOrderBy", "",
"lookupOrderByDesc", false,
"lookupUnique", false,
"lookupAllowAdd", false,
"lookupAllowEdit", false,
"lookupControlType", 0,
"lookupHorizontal", false,
"lookupWhere", "",
"lookupWhereCode", false,
"lookupWhereCodeLang", "cs",
"lookupFreeInput", false,
"lookupListPage", "",
"lookupAddPage", "",
"lookupEditPage", "",
"lookupDependent", false,
"lookupDependentFields", new XVar( "__meta__", 2,
"__object__", new XVar(  ) ),
"lookupAutofillEdit", false,
"lookupAutofillFields", new XVar( "__meta__", 2,
"__object__", new XVar(  ) ),
"fileAddTimestamp", false,
"fileResize", false,
"fileResizeSize", 600,
"fileCreateThumbnail", false,
"fileThumbnailPrefix", "th",
"fileThumbnailSize", 600,
"fileMaxNumber", 0,
"fileSizeLimit", 0,
"fileTotalSizeLimit", 0,
"fileTypes", XVar.Array(),
"fileThumbnailField", "",
"dateEditType", 0,
"dateShowTime", false,
"dateFirstYearFactor", 100,
"dateLastYearFactor", 10,
"dateAllowedDays", XVar.Array(),
"dateAllowedDaysMessage", new XVar( "text", "Invalid week day",
"type", 0 ),
"timeUseTimepicker", false,
"timeShowSeconds", false,
"timeMinutesStep", 1,
"timeConvention", 0,
"pluginInitString", "",
"fieldEvents", new XVar( "__meta__", 2,
"__object__", new XVar( "event", "",
"handlerId", 0 ) ) ) ),
"separateEditViewFormats", false,
"storageProvider", 0,
"amazonPath", "",
"googleDrivePath", "",
"oneDrivePath", "",
"dropboxPath", "",
"googleDrivePublicAccess", true,
"wasabiPath", "",
"defaultSearchOption", "Equals",
"searchOptions", XVar.Array(),
"allSearchOptionsSelected", false,
"filterFormat", new XVar( "__meta__", 0,
"__object__", new XVar( "format", "",
"filterTotals", 0,
"filterTotalsField", "",
"filterMultiselect", 0,
"hideControl", false,
"filterBy", 0,
"sortValueType", 0,
"descendingOrder", false,
"firstVisibleItems", 10,
"multilangCheckedMessage", new XVar( "text", "Checked",
"type", 0 ),
"multilangUncheckedMessage", new XVar( "text", "Unchecked",
"type", 0 ),
"arrFilterIntervals", new XVar( "__meta__", 2,
"__object__", new XVar( "lowerLimit", "",
"upperLimit", "",
"lowerLimitDotNetLanguage", "cs",
"upperLimitDotNetLanguage", "cs",
"lowerLimitType", 0,
"upperLimitType", 0,
"mutilangIntervalText", new XVar( "text", "",
"type", 0 ),
"lowerUsesExpression", false,
"upperUsesExpression", false,
"caseInsensitiveFiltering", false ) ),
"showWithNoRecords", false,
"sliderKnobs", 0,
"sliderStepType", 1,
"sliderStepValue", "1",
"addApplyButton", false,
"pluginInitString", "" ) ),
"parentFilter", "" ) ),
"masterTables", new XVar( "__meta__", 2,
"__object__", new XVar( "table", "",
"detailsKeys", XVar.Array(),
"masterKeys", XVar.Array() ) ),
"detailsTables", XVar.Array(),
"query", null,
"hasEvents", false,
"hasJsEvents", false,
"galleryMode", 2,
"searchSettings", new XVar( "__meta__", 0,
"__object__", new XVar( "caseSensitiveSearch", false,
"searchableFields", XVar.Array(),
"googleLikeSearchFields", XVar.Array(),
"searchSuggest", true,
"highlightSearchResults", true,
"hideDataUntilSearch", false,
"hideFilterUntilSearch", false ) ),
"sortByFields", new XVar( "__meta__", 0,
"__object__", new XVar( "sortOrder", new XVar( "__meta__", 2,
"__object__", new XVar( "fields", new XVar( "__meta__", 2,
"__object__", new XVar( "field", "",
"desc", false ) ),
"label", new XVar( "text", "",
"type", 0 ) ) ) ) ),
"clickActions", new XVar( "__meta__", 0,
"__object__", new XVar( "row", new XVar( "__meta__", 0,
"__object__", new XVar( "action", "noaction" ) ),
"fields", new XVar( "__meta__", 1,
"__object__", new XVar( "action", "noaction" ) ) ) ),
"geoCoding", new XVar( "__meta__", 0,
"__object__", new XVar( "enabled", false,
"latField", "",
"lonField", "",
"addressFields", XVar.Array() ) ),
"labels", new XVar( "__meta__", 0,
"__object__", new XVar( "tableCaption", "",
"fieldLabels", new XVar(  ),
"fieldTooltips", new XVar(  ),
"fieldPlaceholders", new XVar(  ),
"pageTitles", new XVar(  ) ) ) ));
		}
	}

}
