using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Reflection;
using runnerDotNet;
namespace runnerDotNet
{
	public static partial class RunnerSettings
	{
		public static void Apply()
		{
			GlobalVars.runnerProjectSettings = new XVar(new XVar( "restAPIReturnEncodedBinary", true,
"restAPIAuthType", "basic",
"menuIds", new XVar( 0, "main" ),
"tablesAdvSecurity", new XVar( "mother brain chart", new XVar( "table", 2615 ),
"Nomadz Central", new XVar( "table", 2629 ),
"COSMIC KEY", new XVar( "table", 2642 ),
"COSMIC KEY chart", new XVar( "table", 2671 ),
"WORLD LINE", new XVar( "table", 2696 ),
"WORLD LINE chart", new XVar( "table", 2712 ),
"WORLD LINE chart1", new XVar( "table", 2726 ),
"COSMIC KEY OS", new XVar( "table", 2742 ),
"sqlView", new XVar( "table", 2787 ),
"WORLD LINE view", new XVar( "table", 2800 ) ),
"phpSpreadsheet", false,
"ext", "aspx",
"security", new XVar( "projectName", "",
"loginDataSource", "",
"loginForm", 3,
"dynamicPermissions", false,
"dpTablePrefix", "",
"dpTableConnId", "",
"providers", XVar.Array(),
"enabled", false,
"advancedSecurityAvailable", false,
"userGroupsAvailable", false,
"hardcodedLogin", false,
"defaultProviderCode", "",
"adOnlyLogin", false,
"sessionControl", new XVar( "lifeTime", 15,
"sessionName", "wR4WpdqmK73GF5Pf0GbX",
"JWTSecret", "eW2jzl3AhIPdessO7Zwv" ),
"registration", new XVar( "remindMethod", 0,
"hashAlgorithm", 0,
"passwordValidation", new XVar( "strong", false,
"minimumLength", 8,
"uniqueCharacters", 4,
"digitsAndSymbols", 2,
"upperAndLowerCase", false ),
"registerPage", false ),
"captchaSettings", new XVar( "captchaType", 0,
"siteKey", "",
"secretKey", "",
"passesCount", 5 ),
"emailSettings", new XVar( "fromEmail", "",
"usePHPDefinedSMTP", false,
"useBuiltInMailer", false,
"SMTPServer", "localhost",
"SMTPPort", 25,
"SMTPUser", "",
"SMTPPassword", "",
"securityProtocol", 0 ),
"advancedSecurity", new XVar( "allowGuestLogin", false ),
"auditAndLocking", new XVar( "loggingMode", 0,
"loggingTable", new XVar( "connId", "",
"table", "" ),
"loggingFile", "audit.log",
"logSecurityActions", false,
"lockAfterUnsuccessfulLogin", false,
"enableLocking", false,
"lockingTable", new XVar( "connId", "",
"table", "" ),
"tables", new XVar(  ) ),
"twoFactorSettings", new XVar( "available", false,
"required", false,
"enable", true,
"remember", true,
"types", new XVar(  ),
"twoFactorField", "",
"emailField", "",
"phoneField", "",
"codeField", "",
"projectName", "" ),
"staticPermissions", new XVar( "groups", new XVar(  ) ),
"adAdminGroups", XVar.Array(),
"showUserSource", false,
"dbProviderCodes", XVar.Array() ),
"notifications", new XVar( "enabled", false,
"table", new XVar( "connId", "",
"table", "" ) ),
"allTables", new XVar( "mother brain chart", new XVar( "gid", 2615,
"name", "mother brain chart",
"shortName", "mother_brain1",
"type", 9,
"caption", new XVar( "English", "Mother Brain Chart" ),
"connId", "conn",
"color", "8fbc8b",
"originalTable", "" ),
"Nomadz Central", new XVar( "gid", 2629,
"name", "Nomadz Central",
"shortName", "Nomadz_Central",
"type", 4,
"caption", new XVar( "English", "Nomadz Central" ),
"connId", "",
"color", "e07878",
"originalTable", "" ),
"COSMIC KEY", new XVar( "gid", 2642,
"name", "COSMIC KEY",
"shortName", "COSMIC_KEY",
"type", 6,
"caption", new XVar( "English", "COSMIC KEY" ),
"connId", "conn",
"color", "daa520",
"originalTable", "" ),
"COSMIC KEY chart", new XVar( "gid", 2671,
"name", "COSMIC KEY chart",
"shortName", "COSMIC_KEY1",
"type", 9,
"caption", new XVar( "English", "COSMIC KEY Chart" ),
"connId", "conn",
"color", "daa520",
"originalTable", "" ),
"WORLD LINE", new XVar( "gid", 2696,
"name", "WORLD LINE",
"shortName", "WORLD_LINE",
"type", 6,
"caption", new XVar( "English", "WORLD LINE" ),
"connId", "conn",
"color", "e8926f",
"originalTable", "" ),
"WORLD LINE chart", new XVar( "gid", 2712,
"name", "WORLD LINE chart",
"shortName", "WORLD_LINE1",
"type", 9,
"caption", new XVar( "English", "WORLD LINE Chart" ),
"connId", "conn",
"color", "e8926f",
"originalTable", "" ),
"WORLD LINE chart1", new XVar( "gid", 2726,
"name", "WORLD LINE chart1",
"shortName", "WORLD_LINE2",
"type", 9,
"caption", new XVar( "English", "WORLD LINE Chart1" ),
"connId", "conn",
"color", "e8926f",
"originalTable", "" ),
"COSMIC KEY OS", new XVar( "gid", 2742,
"name", "COSMIC KEY OS",
"shortName", "COSMIC_KEY_OS",
"type", 4,
"caption", new XVar( "English", "COSMIC KEY OS" ),
"connId", "",
"color", "cd5c5c",
"originalTable", "" ),
"sqlView", new XVar( "gid", 2787,
"name", "sqlView",
"shortName", "sqlView",
"type", 6,
"caption", new XVar( "English", "sqlView" ),
"connId", "conn",
"color", "00c2c5",
"originalTable", "" ),
"WORLD LINE view", new XVar( "gid", 2800,
"name", "WORLD LINE view",
"shortName", "WORLD_LINE3",
"type", 1,
"caption", new XVar( "English", "WORLD LINE View" ),
"connId", "conn",
"color", "e8926f",
"originalTable", "" ) ),
"tablesByShort", new XVar( "mother_brain1", "mother brain chart",
"Nomadz_Central", "Nomadz Central",
"COSMIC_KEY", "COSMIC KEY",
"COSMIC_KEY1", "COSMIC KEY chart",
"WORLD_LINE", "WORLD LINE",
"WORLD_LINE1", "WORLD LINE chart",
"WORLD_LINE2", "WORLD LINE chart1",
"COSMIC_KEY_OS", "COSMIC KEY OS",
"sqlView", "sqlView",
"WORLD_LINE3", "WORLD LINE view" ),
"tablesByGood", new XVar( "mother_brain_chart", "mother brain chart",
"Nomadz_Central", "Nomadz Central",
"COSMIC_KEY", "COSMIC KEY",
"COSMIC_KEY_chart", "COSMIC KEY chart",
"WORLD_LINE", "WORLD LINE",
"WORLD_LINE_chart", "WORLD LINE chart",
"WORLD_LINE_chart1", "WORLD LINE chart1",
"COSMIC_KEY_OS", "COSMIC KEY OS",
"sqlView", "sqlView",
"WORLD_LINE_view", "WORLD LINE view" ),
"events", XVar.Array(),
"languages", new XVar( 0, new XVar( "name", "English",
"nativeName", "English",
"rtl", false,
"filename", "English.lng" ) ),
"languageNames", new XVar( 0, "English" ),
"defaultLanguage", "English",
"detectDefaultLanguage", true,
"charset", "utf-8",
"codepage", 65001,
"defaultConnID", "conn",
"wrConnectionID", "",
"wizardBuild", "43785",
"projectBuild", "gbbYUe4tk0D6",
"projectTheme", "default",
"projectSize", "normal",
"customErrorMsg", new XVar( "text", "Error occured.",
"type", 0 ),
"cloudSettings", new XVar( "cloudAmazonRegion", "",
"cloudAmazonBucket", "",
"cloudAmazonAccessKey", "",
"cloudAmazonSecretKey", "",
"cloudWasabiRegion", "",
"cloudWasabiBucket", "",
"cloudWasabiAccessKey", "",
"cloudWasabiSecretKey", "",
"cloudGDriveClientId", "",
"cloudGDriveClientSecret", "",
"cloudOneDriveClientId", "",
"cloudOneDriveClientSecret", "",
"cloudOneDriveDrive", "",
"cloudOneDriveAccountType", 0,
"cloudOneDriveDirectoryId", "",
"cloudDropboxClientId", "",
"cloudDropboxClientSecret", "" ),
"mapSettings", new XVar( "embed", true,
"provider", 0,
"apikey", "" ),
"viewPluginsWithJS", XVar.Array(),
"rtlLanguages", new XVar( "English", false ),
"smsSettings", new XVar( "smsProvider", 4,
"iBusername", "",
"iBpassword", "",
"iBsender", "",
"essUsername", "",
"essPassword", "",
"essSender", "",
"gwApiToken", "",
"gwSender", "",
"mbAuth", "",
"mbSender", "",
"twilioSID", "",
"twilioAuth", "",
"twilioNumber", "",
"phoneField", "",
"counryCode", "+1",
"wauUsername", "",
"wauPassword", "",
"wauSender", "" ) ));
		}
	}

}
