using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Reflection;
using runnerDotNet;
namespace runnerDotNet
{
	public static partial class RunnerSettings
	{
		public static void table_WORLD_LINE3()
		{
			GlobalVars.runnerTableSettings.InitAndSetArrayItem(new XVar( "name", "WORLD LINE view",
"type", 1,
"shortName", "WORLD_LINE3",
"pagesByType", new XVar( "add", new XVar( 0, "add" ),
"export", new XVar( 0, "export" ),
"import", new XVar( 0, "import" ),
"list", new XVar( 0, "list" ),
"print", new XVar( 0, "print" ) ),
"pageTypes", new XVar( "add", "add",
"export", "export",
"import", "import",
"list", "list",
"print", "print" ),
"defaultPages", new XVar( "add", "add",
"export", "export",
"import", "import",
"list", "list",
"print", "print" ),
"afterEditDetails", "WORLD LINE view",
"afterAddDetail", "WORLD LINE view",
"detailsBadgeColor", "e8926f",
"sql", "SELECT * FROM \"WORLD LINE view\"",
"deviceHideFields", new XVar( "1", XVar.Array(),
"5", XVar.Array() ),
"query", new XVar( "sql", "SELECT * FROM \"WORLD LINE view\"",
"parsed", true,
"type", "SQLQuery",
"fieldList", new XVar( 0, new XVar( "sql", "*",
"parsed", true,
"type", "FieldListItem",
"alias", "",
"expression", new XVar( "sql", "*",
"parsed", true,
"type", "NonParsedEntity" ),
"encrypted", false,
"columnName", "" ) ),
"fromList", new XVar( 0, new XVar( "sql", "\"WORLD LINE view\"",
"parsed", true,
"type", "FromListItem",
"table", new XVar( "sql", "\"WORLD LINE view\"",
"parsed", true,
"type", "SQLTable",
"columns", XVar.Array(),
"name", "WORLD LINE view" ),
"joinOn", new XVar( "sql", "",
"parsed", false,
"type", "LogicalExpression",
"contained", XVar.Array(),
"unionType", 0,
"column", null ),
"joinList", new XVar( "sql", "",
"parsed", true,
"type", "JoinOn",
"field1", XVar.Array(),
"field2", XVar.Array() ),
"link", 0 ) ),
"where", new XVar( "sql", "",
"parsed", false,
"type", "LogicalExpression",
"contained", XVar.Array(),
"unionType", 0,
"column", null ),
"groupBy", XVar.Array(),
"having", new XVar( "sql", "",
"parsed", false,
"type", "LogicalExpression",
"contained", XVar.Array(),
"unionType", 0,
"column", null ),
"orderBy", XVar.Array(),
"colsIndex", new XVar( 0, new XVar( "fieldIndex", 0,
"orderByIndex", -1,
"groupByIndex", -1,
"whereIndex", -1,
"havingIndex", -1 ) ),
"headSql", "SELECT",
"fieldListSql", "*",
"fromListSql", "FROM \"WORLD LINE view\"",
"orderBySql", "",
"tailSql", "" ),
"originalTable", "",
"originalPagesByType", new XVar( "add", new XVar( 0, "add" ),
"export", new XVar( 0, "export" ),
"import", new XVar( 0, "import" ),
"list", new XVar( 0, "list" ),
"print", new XVar( 0, "print" ) ),
"originalPageTypes", new XVar( "add", "add",
"export", "export",
"import", "import",
"list", "list",
"print", "print" ),
"originalDefaultPages", new XVar( "add", "add",
"export", "export",
"import", "import",
"list", "list",
"print", "print" ),
"searchSettings", new XVar( "caseSensitiveSearch", false,
"searchableFields", XVar.Array(),
"searchSuggest", true,
"highlightSearchResults", true,
"hideDataUntilSearch", false,
"hideFilterUntilSearch", false,
"googleLikeSearchFields", XVar.Array() ),
"connId", "conn",
"clickActions", new XVar( "row", new XVar( "action", "noaction" ),
"fields", new XVar(  ) ),
"geoCoding", new XVar( "enabled", false,
"latField", "",
"lonField", "",
"addressFields", XVar.Array() ),
"whereTabs", XVar.Array(),
"labels", new XVar(  ),
"chartSettings", new XVar(  ),
"dataSourceOperations", new XVar( "selectList", new XVar( "type", "selectList",
"subtype", "sql",
"enabled", true,
"sql", "SELECT * FROM tableName" ) ),
"calendarSettings", new XVar( "categoryColors", XVar.Array() ),
"ganttSettings", new XVar( "categoryColors", XVar.Array() ) ), "WORLD LINE view");
			if(XVar.Equals(XVar.Pack(CommonFunctions.mlang_getcurrentlang()), XVar.Pack("English")))
			{
				GlobalVars.runnerTableLabels.InitAndSetArrayItem(new XVar( "tableCaption", "WORLD LINE View",
"fieldLabels", new XVar(  ),
"fieldTooltips", new XVar(  ),
"fieldPlaceholders", new XVar(  ),
"pageTitles", new XVar(  ) ), "WORLD LINE view");
			}
		}
	}

}
